# Generated by Django 3.2.3 on 2022-01-22 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ecoProject',
            fields=[
                ('prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=60, verbose_name='專案名稱')),
                ('priority', models.CharField(choices=[('0', 'Highest'), ('1', 'Important'), ('2', 'Normal')], default='2', max_length=1, verbose_name='專案級別')),
                ('category', models.CharField(choices=[('00', '年度計畫'), ('01', '人力精實'), ('02', '測試自動化'), ('03', '設備備品'), ('04', '耗材降低'), ('05', '包材管控'), ('06', 'Attrition降低'), ('07', '製程改善'), ('08', '效率提升'), ('09', 'UPH提升'), ('10', '品質提升'), ('11', '自動化提升'), ('12', '報表E化'), ('13', '節能減排'), ('14', '工程機電'), ('15', '其他')], default='00', max_length=2, verbose_name='專案類別')),
                ('status', models.CharField(choices=[('0', 'Ongoing'), ('1', 'Pending'), ('2', 'Closed'), ('3', 'Cancel')], default='0', max_length=1, verbose_name='專案狀態')),
                ('description', models.CharField(default='', max_length=100, verbose_name='專案描述')),
                ('current_stage', models.CharField(choices=[('0', '立案中'), ('1', '需求分析'), ('2', '待排配開發'), ('3', '開發中'), ('4', '驗證中'), ('5', '已上線'), ('6', '取消')], default='0', max_length=1, verbose_name='專案開展階段')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='立案日期')),
                ('start_date', models.DateField(blank=True, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, verbose_name='預計完成日期')),
                ('close_date', models.DateField(blank=True, verbose_name='結案日期')),
                ('dpbg_site', models.CharField(choices=[('0', 'ALL'), ('1', 'GL'), ('2', 'ZZ PE1'), ('3', 'ZZ PE2'), ('4', 'ZZ SUR'), ('5', 'TY'), ('6', 'BZ'), ('7', 'TN')], default='0', max_length=1, verbose_name='廠區')),
                ('pe_department', models.IntegerField(choices=[(0, 'ALL'), (1, 'SFA'), (2, 'IE'), (3, 'AAE'), (4, 'AE'), (5, 'ME'), (6, 'AP'), (7, 'RF'), (8, 'Asset'), (9, 'PDCA'), (10, 'MEDD'), (11, 'CSA'), (12, 'Support')], default=0, verbose_name='部門')),
                ('updates', models.PositiveBigIntegerField(default=0)),
                ('prj_creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
