# Generated by Django 3.2.3 on 2022-01-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoproject',
            name='close_date',
            field=models.DateField(blank=True, default='', verbose_name='結案日期'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='end_date',
            field=models.DateField(blank=True, default='', verbose_name='預計完成日期'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='start_date',
            field=models.DateField(blank=True, default='', verbose_name='開始日期'),
        ),
    ]
