# Generated by Django 3.2.3 on 2022-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjm', '0002_auto_20220122_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoproject',
            name='category',
            field=models.IntegerField(choices=[(0, '年度計畫'), (1, '人力精實'), (2, '測試自動化'), (3, '設備備品'), (4, '耗材降低'), (5, '包材管控'), (6, 'Attrition降低'), (7, '製程改善'), (8, '效率提升'), (9, 'UPH提升'), (10, '品質提升'), (11, '自動化提升'), (12, '報表E化'), (13, '節能減排'), (14, '工程機電'), (15, '其他')], default=0, verbose_name='專案類別'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='close_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='結案日期'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='current_stage',
            field=models.IntegerField(choices=[(0, '立案中'), (1, '需求分析'), (2, '待排配開發'), (3, '開發中'), (4, '驗證中'), (5, '已上線'), (6, '取消')], default=0, verbose_name='專案開展階段'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='description',
            field=models.CharField(default='', max_length=60, verbose_name='專案描述'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='dpbg_site',
            field=models.IntegerField(choices=[(0, 'ALL'), (1, 'GL'), (2, 'ZZ PE1'), (3, 'ZZ PE2'), (4, 'ZZ SUR'), (5, 'TY'), (6, 'BZ'), (7, 'TN')], default=0, verbose_name='廠區'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Highest'), (1, 'Important'), (2, 'Normal')], default=2, verbose_name='專案級別'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Pending'), (2, 'Closed'), (3, 'Cancel')], default=0, verbose_name='專案狀態'),
        ),
    ]
