# Generated by Django 3.2.3 on 2022-02-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjm', '0003_auto_20220122_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatesQueue',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Status Updates')),
                ('next', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='專案描述'),
        ),
    ]
