# Generated by Django 3.2.3 on 2022-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjm', '0005_alter_updatesqueue_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesqueue',
            name='content',
            field=models.TextField(default='', max_length=240, verbose_name='Status Updates'),
        ),
        migrations.AlterField(
            model_name='updatesqueue',
            name='next',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
