# Generated by Django 3.2.3 on 2022-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjm', '0006_auto_20220219_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesqueue',
            name='next',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
