# Generated by Django 3.2.3 on 2022-02-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjm', '0009_auto_20220220_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatesqueue',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='updatesqueue',
            name='next',
        ),
    ]
