# Generated by Django 3.2.3 on 2022-03-02 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pjm', '0010_auto_20220220_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUpdatesQueue',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content', models.TextField(default='', max_length=240, verbose_name='Status Updates')),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=60, verbose_name='任務名稱')),
                ('status', models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Pending'), (2, 'Closed'), (3, 'Cancel')], default=0, verbose_name='任務狀態')),
                ('start_date', models.DateField(blank=True, default='', verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, default='', verbose_name='預計完成日期')),
                ('close_date', models.DateField(blank=True, default='', null=True, verbose_name='結案日期')),
                ('progress', models.IntegerField(default=0, verbose_name='任務進度')),
                ('updates', models.PositiveBigIntegerField(default=0)),
                ('dri', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parentprj', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='pjm.ecoproject')),
            ],
        ),
    ]
