# Generated by Django 3.2.3 on 2022-03-02 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pjm', '0011_task_taskupdatesqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesqueue',
            name='editor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
