# Generated by Django 3.2.3 on 2022-03-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjm', '0012_updatesqueue_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatesqueue',
            name='editor',
        ),
    ]
