# Generated by Django 3.2.3 on 2022-02-21 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[('0', 'Meeting'), ('1', 'NPI'), ('2', 'Task')], default='0', verbose_name='Category')),
                ('content', models.TextField(verbose_name='工作日報')),
                ('start_time', models.DateTimeField(default='', verbose_name='開始時間')),
                ('end_time', models.DateTimeField(default='', verbose_name='結束時間')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加時間')),
                ('attention', models.ManyToManyField(blank=True, related_name='attention', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作日報',
                'verbose_name_plural': '工作日報',
            },
        ),
    ]
