# Generated by Django 3.2.3 on 2022-02-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_alter_calevent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='工作描述'),
        ),
    ]
